language: php
php:
  - 7.2.19
install:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
deploy:
  api_key:
    secure: NMRG5GVs4pQ2stayCFgpiEavIub3U8RxU/8Nhd3ySNn7V6qpomNzygbK2zDZue7bh1d12yKVhVTOHqTAOvhPVSy52q/osKXxrdb3UKV1bXujGkzdf1zv0F6D/cZDgGA9BsQB2ouxrvYiEdC3rJCsTfuWi7eRS5rE3KwdM9j2wo/vI60QT/Tvr+428344zK6WqWPUBaSQob+DfnWZqVHpcf0Q6Yfai92Pt9EERDQuwm6NUo5LO+2cvF9/4P3ZpPhnM720NtRX2HEEzG58OlULCgtpq9RUZxKNFrGUZXJ+ssImM1RtfUG5eDRU8UzkEFoscA8NcgCtZdDYFCBVduiALhIlzSbS/0gFsPi3xz228UWrnRWgxnYMyvi0tqliD/LILAxi7+EXfIn9w6Q4DNlIZuiS7Kaz8WYU7rq9pBxWPjyC2woYPbDy8ip9Fp8maGStfuX8TrnQ21lu3LsnwED37ERaY2z9KM54NIBsgvjxrIfWPkEhbjEnuRHYKzvr+P6aL2L7Mkgw17q4THXSAgxTLb3JbxAyHFGXiMvrLCYHdE4Tg2c7KAr7WvRqKXR/fw3526LCZVgdrY1rCuYhJSGjiBQLe0p5aOPPkT/zpythThmru2FUr4LpxGtcdbmfAXplwLVwvi/PsiGSOQzVR7WUomVVgFDBAfrJi0ZxZGtnl0s=
  app: project-ideas-twitch
  provider: heroku
